### ISSUE TITLE
Kubei not running

### ISSUE THREAD

**Issue by Hounddog** [cisco-open/kubei#68]
We are running kubei behind a proxy. 
I have set everything up as per the readme.

However i am not able to reach the WebUI

`$ kubectl -n kubei get pod -lapp=kubei
NAME                     READY   STATUS    RESTARTS   AGE
kubei-78887848d5-pfsnf   1/1     Running   0          3m39s
`

Grype Server Logs
`2021/12/20 13:42:43 Serving grype server at http://[::]:9991`

Kubei Logs
`time="2021-12-20T14:40:35Z" level=info msg="Webapp is running"
time="2021-12-20T14:40:35Z" level=info msg="Starting Orchestrator server"`

**Comment by FrimIdan** [comment]
@Hounddog Hi, thanks for trying out Kubei.
We will need additional information in order to understand the issue here.
> We are running kubei behind a proxy.

Can you elaborate on that?

> However i am not able to reach the WebUI

Did you run the port-forward command (`kubectl -n kubei port-forward $(kubectl -n kubei get pods -lapp=kubei -o jsonpath='{.items[0].metadata.name}') 8080`)?
If so, what you are getting when browsing to http://localhost:8080/view/ ?
